### ISSUE TITLE
CPU: Add Instruction Debug Information

### ISSUE THREAD

**Issue by mward-sudo** [mward-sudo/z80_undead#5]
## Description
Add debugging information to instruction metadata to support development and debugging tools.

### Technical Details
- Add to Instruction struct:
  - mnemonic: &'static str
  - name: InstructionType enum

### Implementation Steps
1. Create InstructionType enum
2. Add debug fields to Instruction struct
3. Update NOP implementation with debug info
4. Add display/debug trait implementations
5. Add tests for debug information

### Success Criteria
- [x] InstructionType enum defined
- [x] Debug fields added to Instruction
- [x] Display/Debug traits implemented
- [x] Tests added for debug functionality
- [x] Documentation updated

### Dependencies
- [x] #3 

### Estimated Complexity
Small
